### ISSUE TITLE
Mini Hackathon - TODO List

### ISSUE THREAD

**Issue by nikhil153** [nipoppy/nipoppy#62]
## team mr_proc 
- [x] Refactor branches to forks (@michellewang, @bcmcpher, @nikhil153)
- [ ] Standardize run_scripts (@InesGP, @nikhil153, @bcmcpher) 
- [x] PPMI mr_proc_manifest (@michellewang)

## team neurobagel 
- [ ] Test and confirm bagel.csv for tabular and derivatives data (@surchs, @alyssadai, @jarmoza, @rmanaem, @nikhil153)
- [ ] Decide pybids workflow / create bagel.csv from pybids (@surchs, @alyssadai, @nikhil153, @jbpoline)

## team Jacob
- [ ] Develop [dask-queue](https://jobqueue.dask.org/en/latest/) to launch mr_proc run_scripts on HPC (@jacobsanz97, @jeromedockes )

**Comment by jbpoline** [comment]
Looks great to me - @jeromedockes  might be interested in helping reviewing or getting involved in the dask-queue ?

**Comment by jeromedockes** [comment]
> Looks great to me - @jeromedockes  might be interested in helping reviewing or getting involved in the dask-queue ?

Happy to help if I can. It's tomorrow right?

**Comment by nikhil153** [comment]
@jeromedockes yes, tomorrow from 9-12 MTL time.

**Comment by michellewang** [comment]
Closing this issue since we are doing some cleanup in the repo!
